### ISSUE TITLE
Unintended Redirect to  localhost:80 After Clerk Authentication

### ISSUE THREAD

**Issue by mateusdcv93** [The-SaaS-Factory/next-14-saas-boilerplate#5]
I'm experiencing unexpected behavior after successful authentication with Clerk. Upon login, I'm redirected to 
https://localhost:80 instead of the intended application dashboard (including the super admin dashboard).

![image](https://github.com/The-SaaS-Factory/next-14-saas-boilerplate/assets/155934418/858c512e-a106-4212-a0b3-892f2f0f1b34)

Should I add a variable to my .env file to fix the Clerk login redirect issue?

Thanks for your help!

**Comment by RoylerMarichal** [comment]
Hi.. When you run **npm run dev** the project starts you at localhost:3000 or localhost:80 ??

**Comment by mateusdcv93** [comment]
Hey,

I forgot to mention that I'm currently running in production, utilizing EasyPanel with Nixpacks for building. I believe it's accessible on port :80.

![image](https://github.com/The-SaaS-Factory/next-14-saas-boilerplate/assets/155934418/04423df1-b73c-4027-9e25-6e235aceb79d)

**Comment by RoylerMarichal** [comment]
Well, the truth is that this is a bad configuration with clerk, I couldn't tell you exactly..

It only occurs to me that you carefully verify the instance of the application in Clerk which you have in the state variables of that project on that server. Let the url be the same

**Comment by mateusdcv93** [comment]
Maybe a webhook issue? 

![image](https://github.com/The-SaaS-Factory/next-14-saas-boilerplate/assets/155934418/d116bfd0-a1a4-43be-a0a8-4eced682ab75)

Sorry, I'm still a beginner. 

![image](https://github.com/The-SaaS-Factory/next-14-saas-boilerplate/assets/155934418/adeda7bf-de58-49e5-9c81-ed9aab640685)

**Comment by RoylerMarichal** [comment]
Look, there in the webhook, you have to select all the events, or at least those of the user's creation, organization and update of both... But the url is fine...

Check the url of the application in Clerk

If you have the domain configured correctly... It should not be with port: 80 exposed like this
![image](https://github.com/The-SaaS-Factory/next-14-saas-boilerplate/assets/52290307/f3b6b626-65ea-4ae9-ab0a-58958168e64e)

**Comment by mateusdcv93** [comment]
It's like this

![image](https://github.com/The-SaaS-Factory/next-14-saas-boilerplate/assets/155934418/d93371cb-f12d-4b87-9758-2118d9d2db38)

Also, I've tried to add the variables to .env but error still persists

NEXT_PUBLIC_CLERK_SIGN_IN_URL=
NEXT_PUBLIC_CLERK_SIGN_UP_URL=
NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=
NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=

**Comment by RoylerMarichal** [comment]
Already deleted cache and tried with an incognito tab?

**Comment by mateusdcv93** [comment]
Yes, if you notice on the URL it's already with local host when I press to log in: 

![image](https://github.com/The-SaaS-Factory/next-14-saas-boilerplate/assets/155934418/ef5225de-a972-49bf-96dc-53396f0eb947)

I also noticed this on server logs

```
[cause]: n [Error]: Dynamic server usage: Page couldn't be rendered statically because it used `headers`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
      at u (/app/.next/server/chunks/4677.js:193:14358)
      at c (/app/.next/server/chunks/4677.js:193:4893)
      at /app/.next/server/chunks/8090.js:1:42805
      at /app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:182068
      at u (/app/.next/server/chunks/8090.js:1:43371)
      at i (/app/.next/server/chunks/8090.js:1:42248)
      at a (/app/.next/server/chunks/8090.js:1:41743)
      at s (/app/.next/server/chunks/8090.js:1:42665)
      at i (/app/.next/server/chunks/2920.js:1:10504)
      at em (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:131226) {
    description: "Page couldn't be rendered statically because it used `headers`. See more info here: [https://nextjs.org/docs/messages/dynamic-server-error",](https://nextjs.org/docs/messages/dynamic-server-error%22,)
    digest: 'DYNAMIC_SERVER_USAGE'
  }
}
insights
insights
script.js
insights
script.js
Error: Usage of next-intl APIs in Server Components currently opts into dynamic rendering. This limitation will eventually be lifted, but as a stopgap solution, you can use the `unstable_setRequestLocale` API to enable static rendering, see https://next-intl-docs.vercel.app/docs/getting-started/app-router-server-components#static-rendering
    at /app/.next/server/chunks/8090.js:1:42903
    at /app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:182068
    ... 5 lines matching cause stack trace ...
    at em (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:131226)
    at /app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142926
    at Array.toJSON (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:146504) {
  [cause]: n [Error]: Dynamic server usage: Page couldn't be rendered statically because it used `headers`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
      at u (/app/.next/server/chunks/4677.js:193:14358)
      at c (/app/.next/server/chunks/4677.js:193:4893)
      at /app/.next/server/chunks/8090.js:1:42805
      at /app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:182068
      at u (/app/.next/server/chunks/8090.js:1:43371)
      at i (/app/.next/server/chunks/8090.js:1:42248)
      at a (/app/.next/server/chunks/8090.js:1:41743)
      at s (/app/.next/server/chunks/8090.js:1:42665)
      at i (/app/.next/server/chunks/2920.js:1:10504)
      at em (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:131226) {
    description: "Page couldn't be rendered statically because it used `headers`. See more info here: [https://nextjs.org/docs/messages/dynamic-server-error",](https://nextjs.org/docs/messages/dynamic-server-error%22,)
    digest: 'DYNAMIC_SERVER_USAGE'
  }
}
insights
insights
script.js
 ⨯ [Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: 'DYNAMIC_SERVER_USAGE'
}
https://localhost:80/en/home
https://localhost:80/en/home
```

**Comment by RoylerMarichal** [comment]
Well, I have heard that it is problematic to deploy next outside of vercel. My experience has only been in vercel. This error is unknown to me.

**Comment by mateusdcv93** [comment]
I've tried to upload on Vercel but it says that the more than one cronjob it's not possible on the free plan, can we change to another setting? vercel.json

```
{
  "crons": [
    {
      "path": "/api/cron",
      "schedule": "*/1 * * * *"
    }
  ]
}
```

**Comment by RoylerMarichal** [comment]
Yes, you can delete that file without problems

**Comment by mateusdcv93** [comment]
Thank you. I was able to make it work, but now it gives me this error when trying to make the onboarding.
Using Vercel.

![image](https://github.com/The-SaaS-Factory/next-14-saas-boilerplate/assets/155934418/9182104a-2fae-45f5-92f5-9060addbd792)

**Comment by RoylerMarichal** [comment]
This says that once the user is created in clerk it is not being created in the database... Possible causes

1- The database was not deployed: npx prisma db push && npx prisma db seed

2- The address of the webhook in clerk is wrong. It must end in /en/api/clerk, the webhook must also have the actions of creating, updating users and organizations marked

3- The webhook secret needs to be placed in the vercel state variables for it to be accepted
